echo=/bin/echo

ifeq ($(FORCE_GCC),1)
	CXX=g++
	INCLUDE=
	WFLAGS=-Wall

	OFLAGS_full=-O3 -mips4 -mcpu=r10000
	DFLAGS_1=-g -ggdb
	DFLAGS_0= -DNDEBUG

	MISCFLAGS=-fPIC -pthread 
else
	CXX=CC
	INCLUDE=
	#1209: Controlling parameter is true (I use this a lot, eg from <limits>)
	#1506: Warning about implicit conversion. I use these a lot. 

	#1424: Template parameter not used in the argument types. (CC's headers)
	#3201: Parameter not referenced (CC's header files generate lots of these)
	#1110: Statement not reached. these are generated by CC's headers.
	WFLAGS=-fullwarn -woff 3201,1110,1424,1209,1506
	OFLAGS_full=-Ofast -r10000 -mips4
	DFLAGS_1=-g
	DFLAGS_0= -DNDEBUG
	MISCFLAGS=-KPIC -LANG:std
	AR=CC $(WFLAGS) -ar -o
endif

options+=O2Buffer

options_IRIX=O2Buffer

TESTLIB=-L$(X11_L) -lX11 -lGL -ldmedia -lvl -ljpeg

OBJS_IRIX=cvd_src/IRIX/O2buffer.o cvd_src/IRIX/sgi-video.o
TEST_IRIX=test/o2buffer.test
