name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - run: |
           sudo apt-get update
           sudo apt install g++-10 gcc-10 libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - uses: actions/checkout@v2
    - name: setup
      run: mkdir build
    - name: configure
      working-directory: ./build
      run: ../configure
      env: 
        CC: gcc-10
        CXX: g++-10 -Werror -Wno-stringop-overflow
    - name: make
      working-directory: ./build
      run: make
    - name: make test
      working-directory: ./build
      run: make test
  build-test-ubuntu-cmake:
    runs-on: ubuntu-18.04
    steps:
    - run: |
           sudo apt-get update
           sudo apt install g++-10 gcc-10 cmake libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev libswscale-dev
    - uses: actions/checkout@v2
    - name: setup
      run: mkdir build
    - name: configure
      working-directory: ./build
      run: cmake ..
      env: 
        CC: gcc-10
        CXX: g++-10 -Werror -Wno-stringop-overflow
    - name: make
      run: make
      working-directory: ./build
    - name: ctest
      working-directory: ./build
      run: ctest .
  clang-format-ubuntu:
    runs-on: ubuntu-18.04
    steps:
    - run: |
           sudo apt-get update
           sudo apt install clang-format-10
    - uses: actions/checkout@v2
    - name: format
      run: find . \( -name '*.cpp' -o -name '*.h' -o -name '*.cc' -o -name '*.cxx'  \) -a -not -path ./progs/video_iOS/\* | xargs -n 1 clang-format-10 --verbose -i
    - run: |
        if ! git diff-index --exit-code --quiet HEAD; then
            git diff
            exit 1
        fi
  build-test-ubuntu-cmake-light:
    runs-on: ubuntu-18.04
    steps:
    - run: |
           sudo apt-get update
           sudo apt install g++-10 gcc-10 cmake
    - uses: actions/checkout@v2
    - name: setup
      run: mkdir build
    - name: configure
      working-directory: ./build
      run: cmake -DCMAKE_DISABLE_FIND_PACKAGE_PNG=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_JPEG=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_TIFF=TRUE ..
      env: 
        CC: gcc-10
        CXX: g++-10 -Werror -Wno-stringop-overflow
    - name: make
      run: make
      working-directory: ./build
  build-windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: setup
      run: md build 
    - name: configure
      working-directory: ./build
      run: cmake -DCVD_ENABLE_PROGS=OFF -DCVD_ENABLE_TESTS=OFF -DCVD_ENABLE_EXAMPLES=OFF ..
    - name: compile
      working-directory: ./build
      run: msbuild CVD.sln



